# Generated by Django 4.2.5 on 2024-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faturamentosimplificado',
            fields=[
                ('fim_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tur_codigo', models.IntegerField()),
                ('loj_codigo', models.IntegerField()),
                ('ven_codigo', models.IntegerField()),
                ('age_codigo', models.IntegerField()),
                ('fim_data', models.DateField()),
                ('aco_codigo', models.IntegerField()),
                ('fim_tipo', models.CharField(max_length=10)),
                ('tur_numerovenda', models.CharField(max_length=20)),
                ('fim_valorliquido', models.FloatField()),
                ('fim_markup', models.FloatField()),
                ('fim_valorinc', models.FloatField()),
                ('fim_valorincajustado', models.FloatField()),
                ('loj_descricao', models.CharField(max_length=10)),
                ('aco_descricao', models.CharField(max_length=20)),
                ('ven_descricao', models.CharField(max_length=40)),
                ('age_descricao', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'faturamentosimplificado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncomumAgencia',
            fields=[
                ('age_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('age_viagem', models.CharField(max_length=70)),
                ('age_site', models.CharField(blank=True, max_length=180, null=True)),
                ('age_datacadastro', models.CharField(blank=True, max_length=255, null=True)),
                ('age_cnpj', models.CharField(max_length=20)),
                ('age_situacao', models.CharField(max_length=20)),
                ('age_inscricaomunicipal', models.CharField(blank=True, max_length=20, null=True)),
                ('age_cep', models.IntegerField(blank=True, null=True)),
                ('age_rua', models.CharField(blank=True, max_length=70, null=True)),
                ('age_numero', models.IntegerField(blank=True, null=True)),
                ('age_bairro', models.CharField(blank=True, max_length=70, null=True)),
                ('age_cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('age_fone', models.IntegerField(blank=True, null=True)),
                ('age_celular', models.IntegerField(blank=True, null=True)),
                ('age_comissao', models.FloatField()),
                ('age_over', models.FloatField(blank=True, null=True)),
                ('age_markup', models.FloatField(blank=True, null=True)),
                ('age_banco', models.CharField(max_length=20)),
                ('age_agencia', models.IntegerField(blank=True, null=True)),
                ('age_conta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incomum_agencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncomumAgente',
            fields=[
                ('agt_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('age_codigo', models.CharField(max_length=255)),
                ('agt_descricao', models.CharField(max_length=255)),
                ('agt_cpf', models.IntegerField()),
            ],
            options={
                'db_table': 'incomum_agente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncomumUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'incomum_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turisticosituacao',
            fields=[
                ('tur_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tsi_codigo', models.IntegerField()),
                ('tsi_datacadastro', models.DateField()),
                ('usr_codigo', models.IntegerField()),
                ('stu_codigo', models.IntegerField()),
                ('tsi_observacao', models.CharField(blank=True, max_length=90, null=True)),
                ('tsi_markup', models.FloatField(blank=True, null=True)),
                ('tsi_valorcambio', models.FloatField(blank=True, null=True)),
                ('tsi_comissao', models.FloatField(blank=True, null=True)),
                ('tsi_valortaxa', models.FloatField(blank=True, null=True)),
                ('tsi_taxaemissao', models.FloatField(blank=True, null=True)),
                ('tsi_incentivo', models.FloatField(blank=True, null=True)),
                ('tsi_valortarifa', models.FloatField(blank=True, null=True)),
                ('tsi_valorliquido', models.FloatField(blank=True, null=True)),
                ('tsi_valorinc', models.FloatField()),
                ('tsi_valorbase', models.FloatField(blank=True, null=True)),
                ('tsi_valorprejuizo', models.FloatField(blank=True, null=True)),
                ('tsi_markupajustado', models.FloatField(blank=True, null=True)),
                ('tsi_vendareal', models.FloatField(blank=True, null=True)),
                ('tsi_comissaoreal', models.FloatField(blank=True, null=True)),
                ('tsi_incentivoreal', models.FloatField(blank=True, null=True)),
                ('tsi_arredondamentoreal', models.FloatField(blank=True, null=True)),
                ('tsi_diferencacambioreal', models.FloatField(blank=True, null=True)),
                ('tsi_diferencaavista', models.FloatField(blank=True, null=True)),
                ('tsi_incajustado', models.FloatField(blank=True, null=True)),
                ('tsi_diferencataxareal', models.FloatField(blank=True, null=True)),
                ('tsi_percentualcomissao', models.FloatField(blank=True, null=True)),
                ('tsi_percentualincentivo', models.FloatField(blank=True, null=True)),
                ('tsi_cambiotaxareal', models.FloatField(blank=True, null=True)),
                ('tsi_multaincomum', models.FloatField(blank=True, null=True)),
                ('tsi_netoreembolso', models.FloatField(blank=True, null=True)),
                ('tsi_taxareembolso', models.FloatField(blank=True, null=True)),
                ('tsi_vendareembolso', models.FloatField(blank=True, null=True)),
                ('tsi_comissaoreembolso', models.FloatField(blank=True, null=True)),
                ('tsi_incentivoreembolso', models.FloatField(blank=True, null=True)),
                ('tsi_custoajustado', models.FloatField(blank=True, null=True)),
                ('tsi_valoroperacional', models.FloatField(blank=True, null=True)),
                ('tsi_valornota', models.FloatField(blank=True, null=True)),
                ('tsi_valornotaajustado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turisticosituacao',
                'managed': True,
                'unique_together': {('tur_codigo', 'tsi_codigo')},
            },
        ),
    ]
